### ISSUE TITLE
.

### ISSUE THREAD

**Issue by graysuit** [abhibagul/Faster-Blogger-Template#1]

**Comment by abhibagul** [comment]
It seems like the advertisement banner code from the earlier version of the free template. It can be removed after removing the widget from the layout section.

**Comment by graysuit** [comment]
This theme was I liked the most,
As this was simple and clean,

But I don't think code should have these shell codes,
Should be un-obfuscated and unpacked,
So that anyone can view or contribute,
Try to de-ofucticate it if you can.


Okay thanks for time,
I will test it.

Sorry if I used any unethical word.

**Comment by abhibagul** [comment]
https://github.com/abhibagul/Faster-Blogger-Template/blob/master/Faster%20Blogger%20Template.xml#L2073 is not a theme component. it is a widget having ability to be removed from the layout section.

**Comment by graysuit** [comment]
Thanks very much,
I will test it soon,
And check whether it is removable component or not.
Okay,
